### ISSUE TITLE
libvirt Error - Cannot get interface MTU on 'br0': No such device

### ISSUE THREAD

**Issue by xiedeacc** [retspen/webvirtcloud#545]
![image](https://user-images.githubusercontent.com/8072296/194688186-ee688ae3-889c-49a7-b503-a4054d4a7339.png)

**Comment by xiedeacc** [comment]
fixed by 
```

vi  /etc/netplan/01-netcfg.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0:
      dhcp4: no
      dhcp6: no

  bridges:
    br0:
      interfaces: [enp5s0]
      dhcp4: no
      addresses: [192.168.101.20/24]
      gateway4: 192.168.101.1
      nameservers:
        addresses: [192.168.101.1]

netplan apply
```
