### ISSUE TITLE
how to make vm connected to router directly?

### ISSUE THREAD

**Issue by xiedeacc** [retspen/webvirtcloud#546]
I use netplan create a bridge on my ubuntu22.04 host, now my host network works well, but I cannot connect to vm, how to sovle this?

```
vi  /etc/netplan/01-netcfg.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0:
      dhcp4: no
      dhcp6: no

  bridges:
    br0:
      interfaces: [enp5s0]
      dhcp4: no
      addresses: [192.168.101.20/24]
      gateway4: 192.168.101.1
      nameservers:
        addresses: [192.168.101.1]
netplan apply
```

![image](https://user-images.githubusercontent.com/8072296/194706624-1c5338cc-d582-4172-a52e-bb6e597bfa7a.png)
![image](https://user-images.githubusercontent.com/8072296/194706671-505cb9ba-7a04-4025-aec2-f279edd36aa5.png)
